#!/bin/sh

if [ "$#" -ne 2 ]
then
    echo "usage: oplan-psgraph domain task"
    exit 1
fi

exec oplan-386 -subr \
	-no -windows -not -interactive \
	-load help/draw-psgraph \
	-domain $1 -task $2 \
	-do "(draw-psgraph-for-plan)"
